name: projetff
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  hive: ^2.0.0
  hive_flutter: ^1.0.0
  logger: ^1.0.0
  intl: ^0.17.0
  flutter_slidable: ^3.0.1
  table_calendar: ^3.0.0
  cupertino_icons: ^1.0.8
  # Remplacez sqflite et sqlite3 par des alternatives compatibles avec le Web
  sqlite3: ^2.5.0
  sqflite: ^2.0.0
  path_provider: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  # Si vous avez des assets, ajoutez-les ici
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # Si vous utilisez des polices personnalisées
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
